# Prometheus Configuration for Adaptive Market Regime System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'adaptive-regime-system'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# Load rules
rule_files:
  - 'alerts/*.yml'

# Scrape configurations
scrape_configs:
  # The Adaptive Regime System
  - job_name: 'adaptive_regime'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # HeavyDB monitoring
  - job_name: 'heavydb'
    static_configs:
      - targets: ['localhost:9091']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Process exporter for detailed process metrics
  - job_name: 'process_exporter'
    static_configs:
      - targets: ['localhost:9256']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9256